pyproject.toml
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/test_worker.py
tests/test_coordinated_workers/test_worker_status.py

This PR largely refactors the worker hook logic to turn it into a more holistic approach.
All logic that is not conditional on a specific event being run is put in a single method called on `Worker.__init__`.
All the observe() calls that are now redundant have been removed.
This should fix some issues we've been seeing in CI where the pod churns at unexpected points in time, and allows us to resolve the issue without resorting to defer().
An alternative to side-effecting in `__init__` would be to put an "observe all events" hook that queues the holistic reconciler. Danger of that approach is that we have less control about when exactly it gets run relative to other event handlers, which in turn might be relying on its side-effects

Holistic worker logic

---

pyproject.toml
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/test_worker.py

On every event, the workload container gets restarted due to `_update_tls_certificates` and `_set_pebble_layer` always returning True to restart.
- `_update_tls_certificates`
the logic almost always returns True even though the data in relation data might not be different than in the disk
- `_set_pebble_layer`
The `checks` layer is almost always different since pebble automatically adds a `threshold: 3` to the current layer and we don't add that to the new layer.
- Add checks in `_update_tls_certificates` to compare relation data with data on disk
- Add `threshold: 3` to `_add_readiness_check`

Prevent unnecessary restarts

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/test_worker.py
tests/test_coordinated_workers/test_worker_status.py
tox.ini

Intermittent issues in CI where the worker goes into error state during `start` hook.
There could be a race between the resource patch and pebble operations i.e., charm code proceeds beyond a can_connect guard, and then lightkube patches the statefulset and the workload is no longer available.
Add a safeguard to not perform pebble operations if the patch is not done.

Add safeguard when resources patch is not ready

---

pyproject.toml
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/conftest.py
tests/test_coordinated_workers/test_worker.py

There was an issue with the implementation of the retry logic in the "wait for status up" phase of the worker restart.
to test: bump in a worker charm and deploy.
the typical restart block should look like:

adjusted retry logic

---

src/cosl/coordinated_workers/coordinator.py

Currently, the Nginx scrape job we set up in the coordinator (for self-monitoring) is using the wrong port (the Nginx one, instead of the Nginx exporter one).
This PR fixes the scrape job to use the correct port.
Pack an HA solutions using this change, relate to Prometheus, and verify the coordinator target is up.

fix: use the correct port for the nginx exporter

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py

Closes #82.
As the title specifies, we should use the appropriate URL scheme in scrape jobs, i.e., we should `https` when TLS is enabled and `http` otherwise.

fix: use https for scrape jobs when tls is available

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py
src/cosl/coordinated_workers/interface.py
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/conftest.py
tests/test_coordinated_workers/test_coordinator.py
tests/test_coordinated_workers/test_coordinator_status.py
tests/test_coordinated_workers/test_worker.py

sthe s3 interface may give to the coordinator a "tls-ca-chain" that the worker is expected to use when using the provisioned storage bucket.
At the moment we are not doing anything with it, which means Worker charms can't use storage that is behind tls
Also there is a bad assumption within the coordinator's s3 config, that the "endpoint" we receive via the s3 integration has a scheme prefix. We use that to determine whether insecure=True.
Not only insecure=False will not work given we don't give the worker a tls cert for the storage configuration, but also it turns out the s3 interface doesn't always give us a full url, but could also give us a fqdn (i.e. no scheme).
add a field to the cluster schema
coordinator puts there the cert if present in s3 databag, worker picks it up and puts it …

S3 tls cert

---

pyproject.toml
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/conftest.py
tests/test_coordinated_workers/test_worker.py

Tempo config expects CA cert to be in `/usr/local/share/ca-certificates/ca.crt`
Push CA to that location

Push CA cert to workload container's `ROOT_CA_CERT` path

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py
src/cosl/coordinated_workers/interface.py

A coordinator should not publish the config to a worker if a worker has not yet published its own data (like roles and addresses).
Add a guard to check if the worker has already published its data right before we try and send the config to that worker.

Add guard against coordinator publishing worker config

---

src/cosl/coordinated_workers/worker.py

When trying to deploy microservice Mimir with (and without) TF and the bucket in minio is not found, unhelpful tracebacks are found in the Juju debug logs.
```
unit-mimir-read-0: 10:31:31 ERROR unit.mimir-read/0.juju-log mimir-cluster:17: Unexpected exception getting readiness endpoint
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-mimir-read-0/charm/venv/cosl/coordinated_workers/worker.py", line 291, in check_readiness
with urllib.request.urlopen(check_endpoint(self)) as response:
File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
...
File "/usr/lib/python3.10/socket.py", line 705, in readinto
return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```
A **ConnectionResetError** …

Add ConnectionResetError(ConnectionError) for debug logging

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py
src/cosl/coordinated_workers/interface.py
src/cosl/coordinated_workers/nginx.py
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/test_coordinator.py
tests/test_coordinated_workers/test_coordinator_status.py

Loki and Mimir's workload traces are configured using `jaeger_thrift_http` protocol.
Add an optional list `workload_tracing_protocols` to enable coordinators to pass a list of workload protocols they want to receive endpoints to be used by their workers' workloads for tracing.
- Split `charm_tracing` and `workload_tracing` into 2 separate endpoints.
- Push CA cert into charm container when nginx TLS is configured

Add `workload_tracing_protocols` as an arg

---

pyproject.toml
src/cosl/coordinated_workers/worker.py
tests/test_coordinated_workers/test_worker.py
tests/test_coordinated_workers/test_worker_status.py

Fixes https://github.com/canonical/tempo-worker-k8s-operator/issues/50
TLDR:
when the worker is happy and configured, but you want it to go, no event will tell it to stop all services. Instead, it will attempt to restart and keep failing at it, as some of the required resources (s3, a coordinator) might be gone already.
Juju will then see the error status and refuse to clean it up.
This PR changes the Worker logic to ensure that, in the reconcile flow, if the worker isn't ready:
- we wipe all configurations (strictly speaking not necessary, but it felt like the clean thing to do)
- we avoid triggering `.restart()` as we know it should fail
- we update the layer to disable service autorestart (as there is no way to 'remove the layer' altogether), and we stop the services one by one
deploy …

Graceful teardown

---

pyproject.toml
src/cosl/coordinated_workers/coordinator.py
tox.ini

This PR adds a `catalogue` relation consumer to be used by our HA charms.
It's set as _optional_ for now until the rest of the HA charms add the catalogue endpoint to not break the CI.
Tandem PR: https://github.com/canonical/tempo-coordinator-k8s-operator/pull/93
1. Deploy Tempo HA
2. Deploy Catalogue
3. `juju integrate tempo:catalogue catalogue`
4. Open catalogue UI
5. You should see an entry for Tempo that redirects to <tempo_ip>:3200/memberlist UI

Add `catalogue` relation

---

pyproject.toml
src/cosl/rules.py
tests/test_rules_promql.py

Currently, anyone who wants to have up/absent alerts for their charm they would have to do this per charm.
“up” has slightly different semantics between remote-write and scrape:
- if prometheus failed to scrape, then it’s down.
- if grafana agent failed to to remote-write (regardles of whether scrape succeeded) then it’s absent.
To help with centralizing the up/absent rules, we need a convenient way to "inject" alerts on the fly.
Support for generic alerts can be centralised in cos-lib by adding the functionality to add rules from a string in either single-rule or official-rule format. This then allows Prometheus (and Mimir) or Grafana Agent to consume this functionality and have a generic up/absent rule in their library provided by the O11y team using best-practice knowledge. This …

Enable Generic Alert Rules

---

pyproject.toml
src/cosl/__init__.py
src/cosl/grafana_dashboard.py
tests/test_grafana_dashboard.py

- Currently it is not possible to auto generate dashboard uid consistently without code duplication in GrafanaDashboardProvider and COSAgentProvider. 
- The "GrafanaDashboard" class has a confusing terminology: "serialize" and "deserialize" are inconsistent.
In tandem with:
- https://github.com/canonical/grafana-k8s-operator/pull/363
- https://github.com/canonical/grafana-agent-operator/pull/224
- https://github.com/canonical/grafana-agent-k8s-operator/pull/337
Also, deprecate the GrafanaDashboard class.
The new LZMABase64 class is consistent with the following view:
```mermaid
graph LR
dict -->|serialize| json-str
json-str -->|deserialize| dict
json-str -->|compress + base64 encode| compressed-str
compressed-str -->|base64 decode + decompress| json-str
```
This change was prompted by an …

Add dashboard uid generation helper

---

pyproject.toml
src/cosl/cos_tool.py
tox.ini

Addresses https://github.com/canonical/grafana-agent-operator/issues/208.
Leave to chmod to charmcraft.yaml and drop it from the lib.
Currently, CosTool duplicates are still in use, and were patched separately:
- https://github.com/canonical/grafana-k8s-operator/pull/371/files#diff-69ab969563d8e0133c6a9e31a0a235f99a626617c456bc84bb1bd25899e36170
- https://github.com/canonical/prometheus-k8s-operator/pull/664/files#diff-3eb4f4fb71ab351956c8e7b96b07a804995e81540a0d2e94c2f63333c7792f79
- https://github.com/canonical/loki-k8s-operator/pull/485/files#diff-ad7051b5ca68befcdb77d638fcfa686fa902ae8089c8e72cea3c222df01a4597

fix: don't run chmod on cos-tool

---

pyproject.toml
src/cosl/rules.py

This PR attempts to centralize the generic alert rule groups in cos-lib to remove code duplication. It is an extension of this merged PR:
- https://github.com/canonical/cos-lib/pull/115
Tandem PRs:
- https://github.com/canonical/prometheus-k8s-operator/pull/660
- https://github.com/canonical/grafana-agent-operator/pull/232
- https://github.com/canonical/avalanche-k8s-operator/pull/50
Note:
- This will not break any CI since the generic rules existed in the Prometheus and Grafana agent libraries. Those will still exist there until the migration to these rules in `cosl` is complete.
- This PR is not dependent on the status of the tandem PRs, rather they are dependent on this one!

Centralized rules groups for libraries to import

---

tox.ini

Failing unit test in operator framework dependency
on test: `tests/test_coordinated_workers/test_coordinator.py`

pin ops dependency to < 2.18

---

tox.ini

[#1555](https://github.com/canonical/operator/issues/1555) is resolved, and the ops pin can be removed in unit tests
unit tests pass

fix: remove ops pin in unit tests

---

pyproject.toml
src/cosl/coordinated_workers/nginx.py

Our HA solutions running nginx insert a default config for listening on ipv6 addresses. In an environment where ipv6 is disabled, nginx fails to start.
Add a common utility function that can be used by the nginx config to add/remove ipv6-related options.
Tandem PR: TODO

Add a utility function to check for ipv6

---

.github/workflows/distributed-solutions-tests.yaml
pyproject.toml
src/cosl/coordinated_workers/coordinator.py
src/cosl/coordinated_workers/nginx.py
src/cosl/loki_logger.py
tests/test_coordinated_workers/resources/sample_loki_nginx_conf.txt
tests/test_coordinated_workers/resources/sample_loki_nginx_conf_tls.txt
tests/test_coordinated_workers/resources/sample_mimir_nginx_conf.txt
tests/test_coordinated_workers/resources/sample_mimir_nginx_conf_tls.txt
tests/test_coordinated_workers/resources/sample_tempo_nginx_conf.txt
tests/test_coordinated_workers/resources/sample_tempo_nginx_conf_tls.txt
tests/test_coordinated_workers/test_coordinator.py
tests/test_coordinated_workers/test_coordinator_status.py
tests/test_coordinated_workers/test_nginx.py
tox.ini

All our (HA) coordinators generate their own nginx config from scratch although they share a lot of common config.
Extract all shared configuration into `cosl`, and keep only the coordinator-specific parts of the `upstreams` and `locations` blocks, which each coordinator will pass to the shared object as needed.
- We do nginx config generation using `crossplane`, so we lazy load it inside `NginxConfig` to avoid adding a new dependency to `cosl`
Tandem PRs:
- https://github.com/canonical/tempo-coordinator-k8s-operator/pull/155
- https://github.com/canonical/loki-coordinator-k8s-operator/pull/52
- https://github.com/canonical/parca-k8s-operator/pull/444
- https://github.com/canonical/mimir-coordinator-k8s-operator/pull/130
- This introduces a breaking change to the coordinated workers. The …

Lift coordinators' nginx config generation to cosl 

---

pyproject.toml
src/cosl/coordinated_workers/__init__.py

Add a deprecation notice for `coordinated_workers` module in preparation for its migration to a standalone library.
https://github.com/canonical/cos-lib/pull/146

Deprecate `coordinated_workers` module

---

src/cosl/types.py
tests/test_type_convert_stored.py

Many of our libs own the `_type_convert_stored` method:
- graf_dashboard
- graf_datasource
- prom_scrape
- nrpe_exporter
- graf_auth
- ingress_per_unit
This is code duplication.
Cosl now owns this and should be imported from in all our libs.
We know that this function works because it is duplicated in all our libraries and I copied it over. The only difference being additional type checking to pass `cosl` static checks and making it public:

feat: Cosl owns `type_convert_stored`

---

pyproject.toml

Forgot to version bump in:
- https://github.com/canonical/cos-lib/pull/155
Version bump to `1.3.0`

chore: Version bump
